import 'package:ebook_app/nation.dart';

const List<Nation> nations = [
  Nation(
    name: '蒙德',
    flag: 'assets/images/nations/mondstadt.webp',
    god: '巴巴托斯',
    nationElement: 'assets/images/elements/anemo.webp',
    mainCity: 'assets/images/main_city/mondstadt.webp',
    nationStory: [
      "2600年前，蒙德被兩個交戰權力劃分：當時的龍捲魔神和烈風高塔之王，「迭卡拉庇安」(Decarabian) 與北風的狼王，「安德留斯」(Andrius)。因迭卡拉庇安的高塔有颶風的保護，安德留斯無法損傷王都分毫。 雖然迭卡拉庇安保護了他的人民，但他沒有給予他們自由；眾人沒法離開所謂「高塔孤王」的颶風和城邦。",
      "一位無名少年為了目睹藍天、飛鳥，以一個細微的元素精靈（後來成為「巴巴托斯」) 、迭卡拉庇安的前愛人阿莫斯 (Amos) 、和一位無名騎士的幫助，爆發了追求「自由」的戰爭。迭卡拉庇安被擊敗了，但戰爭付出了代價 -- 在抗爭中，無名少年死了。安德留斯沒有選擇成為塵世的風神，化為北風流浪；巴巴托斯成為了新一代的風神，把蒙德的地形修改，用神風吹散冰雪、劈開山巒。魔神戰爭結束之後，他亦成為「塵世七執政」之一。某時段後， 特瓦林之龍出生了，成為巴巴托斯的好朋友。",
      "隨後，巴巴托斯因不願成為新的暴君而離開蒙德，讓蒙德成為自治的自由之邦；蒙德後來被貴族統治。再過一千年，貴族變得愈來愈腐敗，最後變成暴君。巴巴托斯響應奴隸少女溫妮莎的呼喊而再次甦醒，與後者一同掀起推翻貴族的革命。她成立了西風騎士團，以防貴族再次管治蒙德。溫妮莎後來被稱為「蒲公英騎士」，亦重建蒙德教堂。四風也被設立了：安德留斯的靈魂成為北風之狼；特瓦林成為東風之龍；升到天空島的溫妮莎成為西風之鷹；而現任的蒲公英騎士就是南風之獅 (現在是西風騎士團代理團長琴)。",
      "五百年前，坎瑞亞國淪陷後，被煉金術士「金」創造的黑龍杜林襲擊蒙德城。 巴巴托斯召喚東風之龍特瓦林來攻擊杜林，在龍脊雪山上面搏鬥，經過激烈的戰鬥後特瓦林勝利了。但後來特瓦林被杜林的毒血感染，陷入沉睡。",
      "半年前，團長法爾伽帶了一班西風騎士團遠征，留下琴作為代理團長。原神的故事開始時，蒙德城被一個稱「風魔」的龍攻擊。",
    ],
    gods: ["巴巴托斯"],
    festivals: ["羽球節", "風花節", "佳釀節"],
  ),

  Nation(
    name: '璃月',
    flag: 'assets/images/nations/liyue.webp',
    god: '摩拉克斯',
    nationElement: 'assets/images/elements/geo.webp',
    mainCity: 'assets/images/main_city/liyue.webp',
    nationStory: [
      "璃月是提瓦特歷史最悠久的國家。3700年前，摩拉克斯和仙人簽訂了契約以保護璃月港，那就是璃月國的成立。",
      "在璃月港的建立很久以前，提瓦特七大魔神還沒任職而神靈還自由地在世上漫遊的時間，這片將會成為璃月的土地上存有很多村莊。在這個時代，摩拉克斯和塵土之神歸終共同管治現在名為「歸離原」的地方。 這個文明在他們的共同統治和在仙人的保護下變得繁榮昌盛。",
      "魔神戰爭爆發時，這個文明經過激烈戰爭後被摧毀了，而導致歸終的死亡；本來肥沃的荻花州變成沼澤了。 摩拉克斯帶他的人民南向，在天衡山南邊建立璃月港，一直立到今日。為了保護這新的城市，摩拉克斯與仙人簽訂了合約，自己就去與其他惡神作戰。鎮壓了數個魔神，如「漩渦之魔神」，和其他神魔的死去（如「鹽之魔神」赫烏莉亞)， 摩拉克斯成為璃月戰場中的勝者，成為塵世的岩神。",
      "可是，戰後的璃月仍然瘴癘叢生，遍佈妖異。 戰敗魔神朽爛的殘軀將憎恨與怨怒散佈塵世，化為「妖邪」。於是，岩王召喚來仙人中的「夜叉」除滅妖邪；每一個夜叉都代表提瓦特的其中一元素。後來，三個夜叉經歷千年血戰而被魔神的遺憾污染；有的陷入恐懼而發狂，或自相殘殺而死。 只有一個夜叉尚存塵世，另一位不知蹤跡。",
      "每年，摩拉克斯在「七星請仙典儀」正式下降，為璃月人民賜下神諭，指引下一年璃月經營的方向。日常凡務就由璃月七星、商會、和千岩兵處理。",
    ],
    gods: ['摩拉克斯'],
    festivals: ['海燈節'],
  ),
  Nation(
    name: '稻妻',
    flag: 'assets/images/nations/inazuma.webp',
    god: '巴爾澤布',
    nationElement: 'assets/images/elements/electro.webp',
    mainCity: 'assets/images/main_city/inazuma.webp',
    nationStory: [
      "雙生魔神雷電影和雷電真在贏下魔神戰爭後在稻妻設下幕府，雷電真負責政務，善戰的雷電影作為影武者輔助，世人大多不知道兩人共同執政。在數百年前的一場大戰中，雷電真隕落，雷電影承繼雷神之位，對外沿用雷電真的神名「巴爾」，經歷過朋友和親人的離去，雷電影決意追求永恆。",
      "她希望稻妻保持永恆不變，所以頒布了禁止稻妻與其他地區交流的「鎖國令」，還下令幕府收繳能賦予人類元素力的神之眼以穩定國內秩序。而她自身則在內心世界「一心淨土」中修行，以此減少時間帶來的「磨損」，日常政務則由與她外形一樣的人偶「雷電將軍」負責處理。她的眷屬八重神子不太認同她的做法，藉旅行者（玩家角色）到稻妻拜訪雷神之際，八重神子利用旅行者說服雷電影明白當下追求永恆的方式是無效的。在旅行者和八重神子的努力下，雷電影改變了先前的想法，也廢除收繳神之眼的「眼狩令」。",
      "雷電影也開始反思過去管理稻妻的方式，並著手改變人偶的設定。雷電影在設計人偶之初就考慮過自己日後可能會三心兩意，有糾正機制確保自己的「初心」得以踐行。雷電影為了修改人偶的設定，與人偶在次空間戮戰數百年並勝之，向人偶證明自己新的想法經得起挑戰和考驗。在戰鬥中她也獲得雷電真留下的殘魂認可，獲得眷顧稻妻的「神櫻樹」種子，並在過去種下種子，鎖國令也隨之解除。",
    ],
    gods: [],
    festivals: [],
  ),
  Nation(
    name: '須彌',
    flag: 'assets/images/nations/sumeru.webp',
    god: '布耶爾',
    nationElement: 'assets/images/elements/dendro.webp',
    mainCity: 'assets/images/main_city/sumeru.webp',
    nationStory: [],
    gods: [],
    festivals: [],
  ),
  Nation(
    name: '楓丹',
    flag: 'assets/images/nations/fontaine.webp',
    god: '芙卡洛斯',
    nationElement: 'assets/images/elements/hydro.webp',
    mainCity: 'assets/images/main_city/fontaine.webp',
    nationStory: [],
    gods: [],
    festivals: [],
  ),
  Nation(
    name: '納塔',
    flag: 'assets/images/nations/natlan.webp',
    god: '赫布里穆',
    nationElement: 'assets/images/elements/pyro.webp',
    mainCity: 'assets/images/main_city/natlan.webp',
    nationStory: [],
    gods: [],
    festivals: [],
  ),
];
